export const bus = {
  name: "KKKL Express",
  images: [
    "https://cdn.busonlineticket.com/vehicle-images/kkkl-express-1.jpg",
    "https://cdn.busonlineticket.com/vehicle-images/kkkl-express-2.jpg",
  ],
};

export const bookings = [
  {
    bookingID: "BNG123456",
    tripNo: 123456,
    busOperator: "Super Nice Express",
    busType: "Executive (2+1)",
    date: "01/10/2024",
    departureTime: "10:15",
    departureLocation: "Batu Pahat",
    boardingLocation: "Batu Pahat Bus Terminal",
    arrivalTime: "14:15",
    arrivalLocation: "Kuala Lumpur",
    price: "35.00",
    seatNo: "A1",
    status: "Completed",
    purchaseAt: "01/10/2024",
    passengerName: "John Doe",
  },
  {
    bookingID: 2,
    tripNo: 123457,
    busOperator: "Super Nice Express",
    busType: "Executive (2+1)",
    date: "01/10/2024",
    departureTime: "10:15",
    departureLocation: "Batu Pahat",
    boardingLocation: "Batu Pahat Bus Terminal",
    arrivalTime: "14:15",
    arrivalLocation: "Kuala Lumpur",
    price: "35.00",
    seatNo: "A1",
    status: "Completed",
    purchaseAt: "01/10/2024",
    passengerName: "John Doe",
  },
];

export const busSchedule = [
  {
    id: 1,
    name: "Super Nice Express",
    type: "Executive (2+1)",
    duration: "4h",
    departureTime: "10:15",
    departureLocation: "JB Larkin",
    arrivalTime: "14:15",
    arrivalLocation: "Penang Sentral",
    rating: 4.5,
    passengers: 27,
    price: "RM 35.00",
  },
  {
    id: 2,
    name: "Super Nice Express",
    type: "Executive (2+1)",
    duration: "4h",
    departureTime: "10:15",
    departureLocation: "JB Larkin",
    arrivalTime: "14:15",
    arrivalLocation: "Penang Sentral",
    rating: 4.5,
    passengers: 27,
    price: "RM 35.80",
  },
  {
    id: 3,
    name: "Super Nice Express",
    type: "Executive (2+1)",
    duration: "4h",
    departureTime: "10:15",
    departureLocation: "JB Larkin",
    arrivalTime: "14:15",
    arrivalLocation: "Penang Sentral",
    rating: 4.5,
    passengers: 27,
    price: "RM 12.00",
  },
  {
    id: 4,
    name: "Super Nice Express",
    type: "Executive (2+1)",
    duration: "4h",
    departureTime: "10:15",
    departureLocation: "JB Larkin",
    arrivalTime: "14:15",
    arrivalLocation: "Penang Sentral",
    rating: 4.5,
    passengers: 27,
    price: "RM 35.00",
  },
  {
    id: 5,
    name: "Super Nice Express",
    type: "Executive (2+1)",
    duration: "4h",
    departureTime: "10:15",
    departureLocation: "JB Larkin",
    arrivalTime: "14:15",
    arrivalLocation: "Penang Sentral",
    rating: 4.5,
    passengers: 27,
    price: "RM 35.00",
  },
];

export const reviews = [
  {
    id: 1,
    name: "John Doe",
    date: "20/01/2024",
    rating: 4,
    comment:
      "The delay was over an hour which I thought they had pushed us to the next timing slot since there were only 3 passenger for the original allocated time slot. The driver was rude, smoked while driving, and the smell disrupt passenger on board.",
  },
  {
    id: 2,
    name: "John Doe",
    date: "20/01/2024",
    rating: 3,
    comment:
      "The delay was over an hour which I thought they had pushed us to the next timing slot since there were only 3 passenger for the original allocated time slot.",
  },
];

export const policies = [
  "No rescheduling",
  "No cancellation or refund after booking",
  "No refund for no-show or late arrival",
];

export const transactions = [
  {
    transactionNo: "TXN001",
    purchaseAt: "2024-10-01T10:30:00Z",
    purchaseBy: "John Doe",
    paymentType: "Credit Card",
    amountPaid: 150.0,
  },
  {
    transactionNo: "TXN002",
    purchaseAt: "2024-10-02T14:45:00Z",
    purchaseBy: "Jane Smith",
    paymentType: "PayPal",
    amountPaid: 75.5,
  },
  {
    transactionNo: "TXN003",
    purchaseAt: "2024-10-03T09:15:00Z",
    purchaseBy: "Alice Johnson",
    paymentType: "Debit Card",
    amountPaid: 200.0,
  },
  {
    transactionNo: "TXN004",
    purchaseAt: "2024-10-04T16:00:00Z",
    purchaseBy: "Bob Brown",
    paymentType: "Bank Transfer",
    amountPaid: 300.75,
  },
  {
    transactionNo: "TXN005",
    purchaseAt: "2024-10-05T12:30:00Z",
    purchaseBy: "Charlie Davis",
    paymentType: "Cash",
    amountPaid: 120.25,
  },
  {
    transactionNo: "TXN006",
    purchaseAt: "2024-10-06T11:00:00Z",
    purchaseBy: "Emily Clark",
    paymentType: "Mobile Payment",
    amountPaid: 45.99,
  },
  {
    transactionNo: "TXN007",
    purchaseAt: "2024-10-07T13:15:00Z",
    purchaseBy: "David Wilson",
    paymentType: "Credit Card",
    amountPaid: 180.5,
  },
  {
    transactionNo: "TXN008",
    purchaseAt: "2024-10-08T15:00:00Z",
    purchaseBy: "Grace Lee",
    paymentType: "PayPal",
    amountPaid: 99.99,
  },
  {
    transactionNo: "TXN009",
    purchaseAt: "2024-10-09T08:45:00Z",
    purchaseBy: "Michael Harris",
    paymentType: "Debit Card",
    amountPaid: 250.0,
  },
  {
    transactionNo: "TXN010",
    purchaseAt: "2024-10-10T17:30:00Z",
    purchaseBy: "Sarah Wilson",
    paymentType: "Cash",
    amountPaid: 60.0,
  },
];
